[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/rss.xml"
  to = "https://jobhunt-backend.onrender.com/rss.xml"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "https://jobhunt-backend.onrender.com/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
